

version: 2.1


jobs:
  Lint-Docker:
    
    docker:
      - image: python:3.7.3-stretch
    
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            hadolint Dockerfile

  Ekscluster-infrastructure:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ~/repo

    steps:
      - checkout
       
      # - add_ssh_keys:
      #       fingerprints:
      #         - "9f:77:5d:2b:3e:87:26:2a:d8:9c:2c:f2:c8:e1:52:fb"

      - run:
          name: ssh key
          command: |
            ssh-keygen -f id_rsa -t rsa -N ''
      - run:
          name: installing dependencies ( eksctl tool)
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/v0.83.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            mv /tmp/eksctl /usr/local/bin
            # check eksctl version
            eksctl version

      - run:
          name: installing dependencies kubctl
          command: |
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
            aws eks --region us-west-2 update-kubeconfig --name production-$CIRCLE_WORKFLOW_ID
            kubectl version --client

      # - run:
      #     name: installing dependencies kubctl
      #     command: |
      #       curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
      #       mv /etc/kubernetes/kubelet.conf /etc/kubernetes/admin.conf
      #       mkdir .kube
      #       mv config .kube/
      #       chown $(id -u):$(id -g ) $HOME/.kube/config
      #       kubectl version

      # - run:
      #     name: aws-iam-authenticator
      #     command: |
      #       curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.21.2/2021-07-05/bin/linux/amd64/aws-iam-authenticator
      #       chmod +x ./aws-iam-authenticator
            
            
      - run:
          name:
          command: |
            eksctl create cluster \
            --name production-$CIRCLE_WORKFLOW_ID \
            --region us-west-2 \
            --nodegroup-name worker-node-$CIRCLE_WORKFLOW_ID \
            --node-type t3.micro \
            --nodes 2 \
            --nodes-min 1 \
            --nodes-max 2 
            



workflows:
  Default:
    jobs:
      - Lint-Docker
      - Ekscluster-infrastructure
            
